title: My Personal Blog 
author: HishamYUM
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  THIS is my official blog for writing my new topics about programming languages...
  Stay tuned..!!!

# social links
twitter_username: hisham_ouberkni # DO NOT include the @ character, or else the build will fail!
github_username:  hisham06  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
